server:
  port: 8713

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8511/eureka/
spring:
  application:
    name: ZUUL-SERVER

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVICE-FEIGN
    api-b:
      path: /api-b/**
      serviceId: RIBBONSERVER




